name: Selenium - Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
   
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils  # Instala o distutils
          pip install -r requirements.txt
   
      - name: Run tests
        run: pytest ./tests -v --html=./reports/report.html
         
      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: report                
          path: ./reports/report.html          



